name: Build with vcpkg binary cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
   
    - name: Bootstrap vcpkg
      if: runner.os == 'Windows'
      run: |
        cd vcpkg
        ./bootstrap-vcpkg.bat

    - name: Bootstrap vcpkg (Linux)
      if: runner.os == 'Linux'
      run: |
        cd vcpkg
        ./bootstrap-vcpkg.sh
    
    - name: Restore vcpkg cache
      id: vcpkg-cache
      uses: magnesj/vcpkg-cache@1e127d8cb1b7cb26df974dac66d7095a5cf5ec9e
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prefix: msj-test-vcpkg-cache

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Configure CMake
      env:
        VCPKG_FEATURE_FLAGS: "binarycaching" # Possibly redundant, but explicitly sets the binary caching feature flag
        VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release
      
    - name: Run application (Windows)
      if: runner.os == 'Windows'
      working-directory: ${{github.workspace}}/build
      run: .\Release\vcpkg-example.exe
      
    - name: Run application (Linux)
      if: runner.os == 'Linux'
      working-directory: ${{github.workspace}}/build
      run: ./vcpkg-example
